---
title: "Phoenix General Data Dashboard (2008-2020)"
output: 
  flexdashboard::flex_dashboard:
    orientation: column
    vertical_layout: fill
    source: https://github.com/Masaaki-Kato981/Phoenix-Data-Analysis
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(tidyverse)
library(readr)
library(ggplot2)
library(gridExtra)
library(rsconnect)
```

```{r DataLoad, include=FALSE}
median_income_cleaned <- read_csv("median_income_cleaned.csv", show_col_types = FALSE)
median_gross_rent_cleaned <- read_csv("median_gross_rent_cleaned.csv", show_col_types = FALSE)
occupancy_status_cleaned <- read_csv("occupancy_status_cleaned.csv", show_col_types = FALSE)
poverty_status_female <- read_csv("poverty_status_female.csv", show_col_types = FALSE)
poverty_status_male <- read_csv("poverty_status_male.csv", show_col_types = FALSE)
sex_by_age_male <- read_csv("sex_by_age_male.csv", show_col_types = FALSE)
sex_by_age_female <- read_csv("sex_by_age_female.csv", show_col_types = FALSE)
sex_by_edu_male <- read_csv("sex_by_edu_male.csv", show_col_types = FALSE)
sex_by_edu_female <- read_csv("sex_by_edu_female.csv", show_col_types = FALSE)
tenure_cleaned <- read_csv("tenure_cleaned.csv", show_col_types = FALSE)
```

-----------------------------------------------------------------------

Page 1
==

Column{data-width=750, .tabset}
------------------
### Tenure

```{r}
# plot of tenure status 
legends_tenure <- c("Renter Occupied"="#808080","Owner Occupied"="#0000FF")
ggplot(data=tenure_cleaned, aes(x=year)) + 
       geom_line(aes(y =owner_occupied,colour="#0000FF"),colour="#0000FF", size=1.5) + 
       geom_line(aes(y=renter_occupied,colour="#808080"), size=1.5) +
       scale_x_discrete(limits = c(2008,2010,2012,2014,2016,2018,2020), 
                        expand=expansion(mult=c(0.1, .1))) + 
       scale_colour_manual(name="Variable",values = legends_tenure) +
       labs(title="Tenure Status", subtitle="Phoenix, Arizona (2008-2020)", x="Year", y="Households") +
       theme(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5))
```

### Occpuancy

```{r}
# plot of occupancy status
occupied_plot <- ggplot(data=occupancy_status_cleaned, aes(x=year,y=occupied_housing_units)) +
                       geom_line(colour='blue', size=1.5) +
                       scale_x_discrete(limits = c(2008,2010,2012,2014,2016,2018,2020),
                                        expand=expansion(mult=c(0.1, .1))) + 
                       labs(title="Occupancy Status", subtitle="Phoenix, Arizona (2008-2020)", x="", y="Occupied Housing Units") +
                       theme(plot.title = element_text(hjust = 0.5),
                             plot.subtitle = element_text(hjust = 0.5))
vacant_plot <- ggplot(data=occupancy_status_cleaned, aes(x=year,y=vacant_housing_units)) +
                      geom_line(colour='blue', size=1.5) +
                      scale_x_discrete(limits = c(2008,2010,2012,2014,2016,2018,2020),
                                       expand=expansion(mult=c(0.1, .1))) + 
                      labs(x="Year", y="Vacant Housing Units") +
                      theme(plot.title = element_text(hjust = 0.5),
                            plot.subtitle = element_text(hjust = 0.5))

# plot side by side
grid.arrange(occupied_plot, vacant_plot)
```


Column {.tabset}
------------------
### Rent

```{r}
# plot of median gross rent
ggplot(data=median_gross_rent_cleaned, aes(x=year,y=median_gross_rent)) +
       geom_line(colour='blue', size=1.5) +
       scale_x_discrete(limits = c(2008,2010,2012,2014,2016,2018,2020), 
                        expand=expansion(mult=c(0.1, .1))) + 
       labs(title="Median Gross Rent", subtitle="Phoenix, Arizona (2008-2020)", x="Year", y="Median Gross Rent") +
       theme(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5))
```

### Income

```{r}
# plot of median income
ggplot(data=median_income_cleaned, aes(x=year,y=median_income)) +
       geom_line(colour='blue', size=1.5) +
       scale_x_discrete(limits = c(2008,2010,2012,2014,2016,2018,2020), 
                        expand=expansion(mult=c(0.1, .1))) + 
       labs(title="Median Income", subtitle="Phoenix, Arizona (2008-2020)", x="Year", y="Median Income") +
       theme(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5))
```

Page 2
==

Column {.tabset}
------------------
### Education (Male) 1

```{r}
# format data
# Format Data to convert each education degree as a categorical variable
sex_by_edu_male_long <- sex_by_edu_male %>%
  pivot_longer(male_12th_grade_no_diploma:male_doctorate_degree, names_to = "education", values_to = "population")

# subsetting data because population differences is too wide between some degrees
sex_by_edu_male_long1 <- subset(sex_by_edu_male_long, education %in% c("male_bachelor_degree",
                                                                    "male_college_1_or_more_year",
                                                                    "male_hs_graduate_ged_alt") )
sex_by_edu_male_long2 <- subset(sex_by_edu_male_long, education %in% c("male_12th_grade_no_diploma",
                                                                    "male_college_less_than_1_year",
                                                                    "male_associate_degree",
                                                                    "male_professional_school_degree",
                                                                    "male_master_degree",
                                                                    "male_doctorate_degree") )

# plot graph
ggplot(data = sex_by_edu_male_long1, aes(year, population)) +
       geom_line(color = "steelblue", size = 1) +
       geom_point(color="steelblue") + 
       labs(title = "Educational Attainment (Male)",
            subtitle = "Phoenix, Arizona (2008-2020)",
            y = "Population", x = "Year") + 
       facet_wrap(~ education) +
       theme(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5),
             axis.ticks.x = element_blank(),
             axis.text.x = element_blank())
```

### Education (Male) 2

```{r}
ggplot(data = sex_by_edu_male_long2, aes(year, population)) +
       geom_line(color = "steelblue", size = 1) +
       geom_point(color="steelblue") + 
       labs(title = "Educational Attainment (Male) (2008-2020)",
            subtitle = "Phoenix, Arizona",
            y = "Population", x = "Year") + 
       facet_wrap(~ education) +
       theme(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5),
             axis.ticks.x = element_blank(),
             axis.text.x = element_blank())
```

Column{.tabset}
------------------
### Education (Female) 1

```{r}
# Format Data to convert each education degree as a categorical variable
sex_by_edu_female_long <- sex_by_edu_female %>%
  pivot_longer(female_12th_grade_no_diploma:female_doctorate_degree, names_to = "education", values_to = "population")

# subsetting data because population differences is too wide between some degrees
sex_by_edu_female_long1 <- subset(sex_by_edu_female_long, education %in% c("female_bachelor_degree",
                                                                    "female_college_1_or_more_year",
                                                                    "female_hs_graduate_ged_alt") )
sex_by_edu_female_long2 <- subset(sex_by_edu_female_long, education %in% c("male_12th_grade_no_diploma",
                                                                    "female_college_less_than_1_year",
                                                                    "female_associate_degree",
                                                                    "female_professional_school_degree",
                                                                    "female_master_degree",
                                                                    "female_doctorate_degree") )

# plot graph
ggplot(data = sex_by_edu_female_long1, aes(year, population)) +
       geom_line(color = "steelblue", size = 1) +
       geom_point(color="steelblue") + 
       labs(title = "Educational Attainment (Female)",
            subtitle = "Phoenix, Arizona (2008-2020)",
            y = "Population", x = "Year") + 
       facet_wrap(~ education) +
       theme(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5),
             axis.ticks.x = element_blank(),
             axis.text.x = element_blank())
```

### Education (Female) 2
```{r}
ggplot(data = sex_by_edu_female_long2, aes(year, population)) +
       geom_line(color = "steelblue", size = 1) +
       geom_point(color="steelblue") + 
       labs(title = "Educational Attainment (Female)",
            subtitle = "Phoenix, Arizona (2008-2020)",
            y = "Population", x = "Year") + 
       facet_wrap(~ education)  +
       theme(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5),
             axis.ticks.x = element_blank(),
             axis.text.x = element_blank())
```

Page 3 
==

Column
------------------

### Age (Male)
```{r}
# plot for sex by age
# Format Data to convert each age bracket as a categorical variable
sex_by_age_male_long <- sex_by_age_male %>%
  pivot_longer(male_17_and_below:male_75_and_above, names_to = "age_bracket", values_to = "population")

# plot graph
ggplot(data = sex_by_age_male_long, aes(year, population)) +
       geom_line(color = "steelblue", size = 1) +
       geom_point(color="steelblue") + 
       labs(title = "Age Bracket (Male)",
            subtitle = "Phoenix, Arizona (2008-2020)",
            y = "Population", x = "Year") + 
       facet_wrap(~ age_bracket)  +
       theme(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5),
             axis.ticks.x = element_blank(),
             axis.text.x = element_blank())
```


Column
------------------
### Age (Female)
```{r}
# plot for sex by age
# Format Data to convert each age bracket as a categorical variable
sex_by_age_female_long <- sex_by_age_female %>%
  pivot_longer(female_17_and_below:female_75_and_above, names_to = "age_bracket", values_to = "population")

# plot graph
ggplot(data = sex_by_age_female_long, aes(year, population)) +
       geom_line(color = "steelblue", size = 1) +
       geom_point(color="steelblue") + 
       labs(title = "Age Bracket (Female)",
            subtitle = "Phoenix, Arizona (2008-2020)",
            y = "Population", x = "Year") + 
       facet_wrap(~ age_bracket)  +
       theme(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5),
             axis.ticks.x = element_blank(),
             axis.text.x = element_blank())
```

Page 4 
==

Column{.tabset}
------------------
### Above Poverty (Male)
```{r}
# plot for sex by poverty status (above poverty, below poverty)
# Format Data to convert each poverty status as a categorical variable
poverty_status_male_long_above <- poverty_status_male %>%
  pivot_longer(male_income_above_18_24:male_income_above_75_and_above, names_to = "age_bracket", values_to = "population")
poverty_status_male_long_below <- poverty_status_male %>%
  pivot_longer(male_income_below_18_24:male_income_below_75_and_above, names_to = "age_bracket", values_to = "population")


# plot graph
ggplot(data = poverty_status_male_long_above, aes(year, population)) +
       geom_line(color = "steelblue", size = 1) +
       geom_point(color="steelblue") + 
       labs(title = "Age Bracket for Males Above Poverty",
            subtitle = "Phoenix, Arizona (2008-2020)",
            y = "Population", x = "Year") + 
       facet_wrap(~ age_bracket)  +
       theme(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5),
             axis.ticks.x = element_blank(),
             axis.text.x = element_blank())
```

### Below Poverty (Male)
```{r}
ggplot(data = poverty_status_male_long_below, aes(year, population)) +
       geom_line(color = "steelblue", size = 1) +
       geom_point(color="steelblue") + 
       labs(title = "Age Bracket for Males Below Poverty",
            subtitle = "Phoenix, Arizona (2008-2020)",
            y = "Population", x = "Year") + 
       facet_wrap(~ age_bracket)  +
       theme(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5),
             axis.ticks.x = element_blank(),
             axis.text.x = element_blank())
```

Column{.tabset}
------------------

### Above Poverty (Female)
```{r}
# plot for sex by poverty status (above poverty, below poverty)
# Format Data to convert each poverty status as a categorical variable
poverty_status_female_long_above <- poverty_status_female %>%
  pivot_longer(female_income_above_18_24:female_income_above_75_and_above, names_to = "age_bracket", values_to = "population")
poverty_status_female_long_below <- poverty_status_female %>%
  pivot_longer(female_income_below_18_24:female_income_below_75_and_above, names_to = "age_bracket", values_to = "population")


# plot graph
ggplot(data = poverty_status_female_long_above, aes(year, population)) +
       geom_line(color = "steelblue", size = 1) +
       geom_point(color="steelblue") + 
       labs(title = "Age Bracket for Females Above Poverty",
            subtitle = "Phoenix, Arizona (2008-2020)",
            y = "Population", x = "Year") + 
       facet_wrap(~ age_bracket)  +
       theme(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5),
             axis.ticks.x = element_blank(),
             axis.text.x = element_blank())
```

### Below Poverty (Female)
```{r}
ggplot(data = poverty_status_female_long_below, aes(year, population)) +
       geom_line(color = "steelblue", size = 1) +
       geom_point(color="steelblue") + 
       labs(title = "Age Bracket for Females Below Poverty",
            subtitle = "Phoenix, Arizona (2008-2020)",
            y = "Population", x = "Year") + 
       facet_wrap(~ age_bracket)  +
       theme(plot.title = element_text(hjust = 0.5),
             plot.subtitle = element_text(hjust = 0.5),
             axis.ticks.x = element_blank(),
             axis.text.x = element_blank())
```


